# This image provides a Node.js environment, suitable for most JavaScript projects.
image: node:latest

# Define the stages involved in the pipeline
stages:
  - install
  - build
  - docker-deploy

# Cache node_modules to speed up subsequent builds
cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build
  # This keeps the build artifacts for later stages or downloading
  artifacts:
    paths:
      - build/

docker-deploy:
  stage: docker-deploy
  script:
    - echo "Building Docker image..."
    - docker build -t revend-frontend:latest .
    - echo "Running Docker container..."
    - docker run --name revend-fe-container -p 3000:3000 --network revend-network -d revend-frontend:latest
  only:
    - main